### ISSUE TITLE
Issues with sleep

### ISSUE THREAD

**Issue by Swimming33** [jamesfawcett/Thinkpad-X2100-51nb-OpenCore-Hackintosh#4]
Hi James! As always... I really do wanna say I'm grateful for the X2100 opencore config you've posted, and understand it's a side-project! Any help is appreciated, but not required with something like this!

Anyways, I'm currently having difficulties with getting sleep to work with Monterey (12.3). When the lid is closed, the laptop display does turn off, and it does require a login upon reopening... but I'm under the suspicion it's not really entering sleep mode. The battery drains quickly when in this quasi-sleep, the fans ramp up, and the little moon icon doesn't turn on (the most important part, of course). For now I've just been turning the machine off everytime I'd normally sleep (bootup is quick enough to make this possible), but if you have any advice on what to do to attempt to get sleep actually working, I'd be grateful!

**Comment by Swimming33** [comment]
(Also, the volume is always at max whenever the computer wakes up, but I don't wanna be picky in fixing problems lol)

**Comment by jamesfawcett** [comment]
Hi @Swimming33 

That's good to know you're still using it too! Sorry I've neglected to update this repo for a while, but I use my X2100 as my daily machine, I love it!

I've switched to MacBookPro16,1 but this repo was a few versions behind. I've just updated everything up to date with where I am now. Now that it's on MacBookPro16, the power management seems better, the fan curves are better (and quieter when needed too!)

I also have the volume bug, and same for brightness too actually! I never really thought about it, but needs fixing.

I've changed Framebuffers too and everything seems happier now, do you want to update yours to same as mine and we can fix these bits? I was having issues where certain websites would ramp the CPU usage right up, like some kind of memory leak. This is all now resolved, but I don't think that would affect you on Monterey.

For sleep - I am also having that issue too. I thought it was because I'm using Ventura, but as you are having same issue on Monterey it must be an issue I've introduced because mine hibernated well on Monterey. 

Do you have Hackintool, and if so, could you open the Power tab and see if your settings are in green?

PS Ventura is awesome, and using iPhone as webcam in a 3D printed magsafe holder solves the issue of having no web cam! :)

**Comment by Swimming33** [comment]
Hey @jamesfawcett ,
Thanks for the update! I too use the X2100 as my daily machine, so this whole thing is a godsend! 
Updated to the new version of the repo, and do appear to be getting better power mangement and fan curves as suggested. If you wanna work on fixing the Framebuffers with me, I have no problem with that! I also hadn't updated to Ventura because I was afraid that it wouldn't work, but hearing of your success definately has me considering it!  

Regarding sleep... I've opened up Hackintool and it did seem to disagree regarding how I had hibernatemode set to 3 instead of 0. So I've gone ahead and let it change that, it might improve sleep, we shall see!

**Comment by jamesfawcett** [comment]
Thanks @Swimming33 

I think the main issue is I've lost track of bits and pieces - I've definitely got some experimental bits enabled too.

My desktop machine is also a Hackintosh (i9 10900k) which I am a bit more OCD with the config! 

Before this, I used my [X201 hackintosh](https://github.com/jamesfawcett/Thinkpad-X201-Hackintosh-Catalina) daily, and I still use it occasionally too! 

This machine definitely ran better on Big Sur. Ventura and Monterey seem about the same.

I don't know if you have seen, but the USB mapping guide changed with Monterey. Since I last did these the new recommended way, the docs seem to have updated again: https://dortania.github.io/OpenCore-Post-Install/usb/manual/manual.html#finding-your-usb-ports

I think the next things I will work on is:

- Look for solution for weird behaviour after sleep
- Redo/check the USB maps , I'm not convinced they are using the full usb3 potential
- Revisit sleep (although I think this might be to do with USB maps (again!))
- Volume/Brightness memory
- Get rid of old lingering kexts/drivers that have been disabled for a while now

I'm tempted though to just run through the full Opencore guide again from the start just to see if there's anything changed. 

PS- sleep is working for me just tested, closing the lid works too, but, I get weirdness when waking up. Certain apps wont open such as Whatsapp until II reboot.

**Comment by Swimming33** [comment]
> I'm tempted though to just run through the full Opencore guide again from the start just to see if there's anything changed.

 @jamesfawcett hey, if you want to, I can say I'd be pretty grateful haha! Either way, whatever updates you can put out are appreciated, it's fun to daily driving MacOS on this weird frankenpad

**Comment by jamesfawcett** [comment]
Hi @Swimming33 what motherboard does your machine use?

My X2100 sadly died. I can't get it to boot up, so I've ordered a 5th batch 10710u version to swap to.

**Comment by Swimming33** [comment]
@jamesfawcett I’ve got a 4th batch board with a 10710u.  
  
Obviously sorry to hear about yours up and dying, only obviously thing I can think of is that maybe it has to do with the EC chip problem that plagued 4th batch boards (though I wouldn’t think that would fully prevent booting). Did you have the resistor installed to fix that?

**Comment by jamesfawcett** [comment]
@Swimming33 this is the first I've heard of EC Chips and resisters, it's news to me! I was sat with a multimeter at the weekend tracing back. Power gets to the board, and I can follow it as far as my eyes will let me, there's voltage present but none of the LED status lights come on and nothing responds. Jacky from cnmods thinks it might be the processor. To me, its a good excuse to upgrade to hexacore anyway! :)

That's good to hear yours is working with the 10710u too though! 

I've also bought the upgraded fan assembly with the extra copper heat pipes.

**Comment by Swimming33** [comment]
@jamesfawcett might as well give the info out, not like you have much to lose if it’s already dead :P 

https://www.xyte.ch/2021/12/14/x2100-me-bios-ec-and-coreboot/
Putting a 1k resistor on a specific spot on the board should fix problems experienced with Intel ME on the board. Surprised you haven’t encountered any issues with this before though, it’s basically the issue that plagued most X2100 owners (and would introduce almost 20 seconds to each boot)


I had to do this myself, have a fun look at the the sh*tty solder job i did 😛
![B735F03C-09A7-472B-9322-84713B2448DE](https://user-images.githubusercontent.com/61389188/200310190-fa2406e6-ab90-4c10-bf3e-1505ac14a6b0.png)

**Comment by jamesfawcett** [comment]
Thanks @Swimming33 

I checked my board, I don't have that resistor, but mine is really quick to boot. Mine was originally from KKMod Shop though I wonder if he's fixed the same issue another way. I found a few nice solutions whilst stripping it down. 

![image](https://user-images.githubusercontent.com/5245272/200341065-1871fc1b-2097-4a50-9716-c9839b98d6d6.png)

Interesting to see the extra cooling branches on your cooler! 

I am tempted to try the 1k resister mod on my dead board, just to see if it responds, but I don't have great hope that it will!

**Comment by jamesfawcett** [comment]
I forgot to mention - I've never updated the bios on mine. Maybe that's also why I don't have issues (from reading the link you gave)

**Comment by jamesfawcett** [comment]
Hey @Swimming33 

I got my 5th batch board today, installed and working but I have the slow boot issues. My booting experience pretty much matches this: 

https://forum.thinkpads.com/viewtopic.php?t=132777

I also cannot boot an Efi from an internal drive, I have to boot from an external USB. Temperatures are cooler though with the extra heat pipes! 

The motherboard that arrived was definitely not new, quite a few signs of wear on it, but I don't mind if it works :) 

![image](https://user-images.githubusercontent.com/5245272/206040964-6d9daef9-9e76-48c0-a8f2-4220f2bb8a85.jpeg)

**Comment by Swimming33** [comment]
Glad to hear you were able to get a board at least, new or otherwise! Those boot issues are definitely a result of the mobo production error I mentioned before (along with the fix). Exactly the issue I was having until I installed the resistor. Obviously, there’s a slight risk involved with the fix, but it should *definitely* resolve the issue in this circumstance. If I can do it, and I’m a total dummy with a soldering iron, I have a feeling it shouldn’t be too hard for you! Lmk if you decide to try the fix.

**Comment by Swimming33** [comment]
(@jamesfawcett, no clue if you get alerted unless I tag you, so extra comment with a tag)

**Comment by jamesfawcett** [comment]
Thanks for this @Swimming33 ! Do you remember which wattage resister you ordered? Thanks for your help. I'm ok with a soldering iron so I'll match yours :)

**Comment by Swimming33** [comment]
> Thanks for this @Swimming33 ! Do you remember which wattage resister you ordered? Thanks for your help. I'm ok with a soldering iron so I'll match yours :)

@jamesfawcett just checked, I went with a 1/4 W, 5% tolerance, 1k ohm resistor, and it works perfectly

**Comment by jamesfawcett** [comment]
Perfect thank you @Swimming33 ! I ordered 1/6 resisters, but I also sent your photo to the seller and he sent me 1/4 - he spotted my mistake! I will solder when they arrive.

In the meantime this new motherboard is doing great! I upgraded the bios to latest as I wasn't sure what it was running.

I had to split out the EFI files, motherboard/bios doesn't like having all three EFI (Win 7, Win 10 and Mac) all on the same drive, even if I cleared the NVRAM and re-added them one by one. I had to put Windows on the NVMe and Mac EFI on the SATA.

I can't boot Windows 7 despite it being the exact same hard drives, not sure if its a driver issue or a bios setting but I just get a black screen after the Windows logo, I can hear it running in the background. I just used Windows 7 for some old car diagnostic programs. 

After the initial issues, I was slightly regretting my decision spending the money and fixing this, the motherboard cost more than the price of an M1 mac, but now its up and running I remember why we love these machines! It's super fast on this i7 processor too! 

I bought some iPad speakers, they're going in when I do the soldering fix. I saw people also use Blackberry passport speakers which apparently sound quite good too!

**Comment by Swimming33** [comment]
@jamesfawcett let me know how the iPad speakers go, I'm still just using the ones it came with (so the original X201 speakers), since I'm lazy. So sue me. Also, I remember you talked about updating the opencore EFI before your last unit died, I don't know if the one currently on github is your most recent "update" so to speak but if it isn't... you think you can just throw the newest one up? Obviously no worries either way

**Comment by jamesfawcett** [comment]
Hi @Swimming33 latest one should be in place now from this evening. 

What I've found is the strange issue I had previously where after sleep, apps wouldn't open is now fixed. But.. Bluetooth seems to be taking up a load of resources after sleep, 25%+ cpu. If I toggle Bluetooth it goes back to normal.

Just another strange bug to add to the list! I'm using an a different Wi-Fi/Bluetooth card at the minute because I snapped the ipex-4 to ipex-1 heads off my adapter board everything works though still it's still native supported, I can't live without airdrop! 

You need to give Ventura a go if you haven't already!

**Comment by Swimming33** [comment]
@jamesfawcett I probably shoudlve looked *before* asking. I’ll give it a go tonight, along with Ventura

**Comment by Swimming33** [comment]
@jamesfawcett just updated my EFI, works great! So I took the big step... and am on Ventura! So far so good (obvs all the previous issues with sleep not working still apply, but baby steps!). My biggest fear was that SmartScroll would have issues, but it seems to still work a-okay. Basically a necessity for me personally to use the trackpoint on MacOS!

**Comment by Swimming33** [comment]
@jamesfawcett coming back to this—with the latest release of your config, i've completely reinstalled my setup Sonoma and everything works... except sleep, which still doesn't. Right now it turns on the screen's backlight when returning from sleep, but there's nothing on the screen (and I don't think it's actually doing anything). Ugh. Convinced it's some weird BIOS thing, or my mobo is just cursed lol.  
 
Is there anything obvs you can think of in the BIOS that might be affecting the sleep? I've futzed with it a bit, turned off overclocking/undervolting and anything even mildly I can think might be causing it, but no matter what I change the results are the same. I'm about 3 minutes away from begging you to just record your entire BIOS config 😅 

Obviously no matter what I'm glad you've put this together. And free support is _not_ required from you, im just hopeful you got ideas

**Comment by Swimming33** [comment]
(and just curious if you installed the transistor on your board to fix the ME issues, completely unrelated)
